package net.syarihu.resourcepruner.gradle.task

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.SetProperty
import org.gradle.work.DisableCachingByDefault
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import java.nio.file.Path

/**
 * Base task for resource pruner operations.
 */
@DisableCachingByDefault(because = "Resource pruning tasks depend on external file system state and should not be cached")
abstract class BaseResourcePrunerTask : DefaultTask() {
  /**
   * Patterns (regular expressions) for resource names to exclude from pruning.
   */
  @get:Input
  @get:Optional
  abstract val excludeResourceNamePatterns: ListProperty<String>

  /**
   * Resource types to target for pruning.
   * If empty, all resource types are targeted.
   */
  @get:Input
  @get:Optional
  abstract val targetResourceTypes: SetProperty<String>

  /**
   * Resource types to exclude from pruning.
   * Resources of these types will be preserved even if unused.
   */
  @get:Input
  @get:Optional
  abstract val excludeResourceTypes: SetProperty<String>

  /**
   * Resource directories to scan for resources.
   */
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val resDirectories: ConfigurableFileCollection

  /**
   * Source directories to scan for resource usage.
   */
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceDirectories: ConfigurableFileCollection

  /**
   * Whether to perform cascade pruning.
   * When enabled, the pruner will repeatedly scan and remove unused resources
   * until no more unused resources are found (max 5 iterations).
   */
  @get:Input
  @get:Optional
  abstract val cascadePrune: Property<Boolean>

  /**
   * Maximum number of cascade iterations.
   */
  @get:Internal
  protected val maxCascadeIterations: Int = 5

  /**
   * Compiles exclude patterns to Regex objects.
   */
  protected fun compileExcludePatterns(): List<Regex> = excludeResourceNamePatterns.get().map { it.toRegex() }

  /**
   * Filters out resource directories under the build directory.
   *
   * Build directory resources (e.g., those generated by the Google Services plugin
   * or Firebase) are auto-generated and should not be targets for pruning.
   */
  protected fun filterSourceResDirectories(resDirs: List<Path>): List<Path> {
    val buildDir = project.layout.buildDirectory.get().asFile.toPath()
    return resDirs.filterNot { it.startsWith(buildDir) }
  }
}
