package net.syarihu.resourcepruner.example

import android.os.Bundle
import android.view.LayoutInflater
import android.view.ViewGroup
import app.cash.paraphrase.getString
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.RecyclerView
import net.syarihu.resourcepruner.example.databinding.ActivityMainBinding
import net.syarihu.resourcepruner.example.databinding.ItemViewbindingOnlyBinding

/**
 * Example activity to demonstrate resource-pruner-plugin.
 *
 * This activity uses:
 * - R.layout.activity_main (via ViewBinding)
 * - R.layout.item_viewbinding_only (via ViewBinding ONLY - no R.layout.xxx reference)
 * - R.string.app_name (via AndroidManifest)
 * - R.string.hello_world (directly)
 * - R.string.greeting_format (via Paraphrase FormattedResources)
 * - R.string.count_format (via Paraphrase FormattedResources)
 * - R.color.primary (via theme/styles)
 * - R.drawable.ic_used_icon (directly)
 *
 * Resources NOT used (should be pruned):
 * - R.string.unused_string
 * - R.string.another_unused
 * - R.string.deprecated_message
 * - R.drawable.ic_unused_icon
 * - R.color.unused_color
 * - R.layout.layout_unused
 * - R.menu.menu_unused
 */
class MainActivity : AppCompatActivity() {

  private lateinit var binding: ActivityMainBinding

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    binding = ActivityMainBinding.inflate(layoutInflater)
    setContentView(binding.root)

    // Use some resources directly
    binding.textView.text = getString(R.string.hello_world)
    binding.imageView.setImageResource(R.drawable.ic_used_icon)

    // Use Paraphrase-generated formatted strings (ICU message format)
    // FormattedResources is generated by the Paraphrase plugin
    // NOTE: greeting_format is used, but unused_paraphrase_format is NOT called
    val greeting = getString(FormattedResources.greeting_format(name = "World"))

    // Log for demonstration
    android.util.Log.d("MainActivity", "Greeting: $greeting")
  }

  /**
   * Example ViewHolder that uses item_viewbinding_only.xml ONLY via ViewBinding.
   *
   * This demonstrates that ViewBindingUsageDetector correctly detects
   * ItemViewbindingOnlyBinding usage without any R.layout.xxx reference.
   */
  class ItemViewHolder(
    private val binding: ItemViewbindingOnlyBinding,
  ) : RecyclerView.ViewHolder(binding.root) {

    fun bind(title: String) {
      binding.itemTitle.text = title
    }

    companion object {
      fun create(parent: ViewGroup): ItemViewHolder {
        val binding = ItemViewbindingOnlyBinding.inflate(
          LayoutInflater.from(parent.context),
          parent,
          false,
        )
        return ItemViewHolder(binding)
      }
    }
  }
}
