package net.syarihu.resourcepruner.example

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.RecyclerView
import app.cash.paraphrase.getString
import net.syarihu.resourcepruner.example.databinding.ActivityMainBinding
import net.syarihu.resourcepruner.example.databinding.ItemViewbindingOnlyBinding
import net.syarihu.resourcepruner.examplelib.R as LibR
import net.syarihu.resourcepruner.examplelib.R as R_exampleLib
import net.syarihu.resourcepruner.examplelib.databinding.LayoutLibUsedBinding

/**
 * Example activity to demonstrate resource-pruner-plugin.
 *
 * This activity uses:
 * - R.layout.activity_main (via ViewBinding)
 * - R.layout.item_viewbinding_only (via ViewBinding ONLY - no R.layout.xxx reference)
 * - R.string.app_name (via AndroidManifest)
 * - R.string.hello_world (directly)
 * - R.string.greeting_format (via Paraphrase FormattedResources)
 * - R.color.primary (via theme/styles)
 * - R.drawable.ic_used_icon (directly)
 *
 * Library resources used (from example-lib module):
 * - R.string.lib_used_string (directly via LibR alias)
 * - R.string.lib_common_message (directly via R_exampleLib alias - underscore style)
 * - R.drawable.ic_lib_used_icon (directly via LibR alias)
 * - R.layout.layout_lib_used (via ViewBinding)
 *
 * Resources NOT used (should be pruned):
 * - R.string.unused_string
 * - R.string.another_unused
 * - R.string.deprecated_message
 * - R.drawable.ic_unused_icon
 * - R.color.unused_color
 * - R.layout.layout_unused
 * - R.menu.menu_unused
 *
 * Library resources NOT used (should be pruned from example-lib):
 * - R.string.lib_unused_string
 * - R.string.lib_deprecated_message
 * - R.drawable.ic_lib_unused_icon
 * - R.layout.layout_lib_unused
 */
class MainActivity : AppCompatActivity() {

  private lateinit var binding: ActivityMainBinding

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    binding = ActivityMainBinding.inflate(layoutInflater)
    setContentView(binding.root)

    // Use some resources directly
    binding.textView.text = getString(R.string.hello_world)
    binding.imageView.setImageResource(R.drawable.ic_used_icon)

    // Use Paraphrase-generated formatted strings (ICU message format)
    // FormattedResources is generated by the Paraphrase plugin
    // NOTE: greeting_format is used, but unused_paraphrase_format is NOT called
    val greeting = getString(FormattedResources.greeting_format(name = "World"))

    // Log for demonstration
    Log.d("MainActivity", "Greeting: $greeting")

    // Use resources from example-lib module
    // These usages should prevent the library resources from being pruned
    val libMessage = getString(LibR.string.lib_used_string)
    Log.d("MainActivity", "Library message: $libMessage")

    // Use resources from example-lib module with underscore-style alias (R_exampleLib)
    // This demonstrates that import aliases with underscores are correctly detected
    val libCommonMessage = getString(R_exampleLib.string.lib_common_message)
    Log.d("MainActivity", "Library common message: $libCommonMessage")

    // Use library drawable
    binding.imageView.setImageResource(LibR.drawable.ic_lib_used_icon)
  }

  /**
   * Example ViewHolder that uses item_viewbinding_only.xml ONLY via ViewBinding.
   *
   * This demonstrates that ViewBindingUsageDetector correctly detects
   * ItemViewbindingOnlyBinding usage without any R.layout.xxx reference.
   */
  class ItemViewHolder(
    private val binding: ItemViewbindingOnlyBinding,
  ) : RecyclerView.ViewHolder(binding.root) {

    fun bind(title: String) {
      binding.itemTitle.text = title
    }

    companion object {
      fun create(parent: ViewGroup): ItemViewHolder {
        val binding = ItemViewbindingOnlyBinding.inflate(
          LayoutInflater.from(parent.context),
          parent,
          false,
        )
        return ItemViewHolder(binding)
      }
    }
  }

  /**
   * Example ViewHolder that uses layout_lib_used.xml from the library module via ViewBinding.
   *
   * This demonstrates that multi-module ViewBinding usage is correctly detected.
   * The plugin should scan this app module's source code when analyzing example-lib's resources.
   */
  class LibraryItemViewHolder(
    private val binding: LayoutLibUsedBinding,
  ) : RecyclerView.ViewHolder(binding.root) {

    fun bind(message: String) {
      binding.libTextView.text = message
    }

    companion object {
      fun create(parent: ViewGroup): LibraryItemViewHolder {
        val binding = LayoutLibUsedBinding.inflate(
          LayoutInflater.from(parent.context),
          parent,
          false,
        )
        return LibraryItemViewHolder(binding)
      }
    }
  }
}
